### ISSUE TITLE
Suggestion to update the Readme

### ISSUE THREAD

**Issue by zjean** [modem7/docker-borgmatic#100]
Hi, thanks for this great docker image!
Since some days, I have an issue starting and stopping my containers from the pre_backup script.
I am mounting my /var/run/docker.sock into the container.

When calling below script from within the container, I get the following response:
```
echo -ne "POST /v1.42/containers/wallabag/start HTTP/1.1\r\nHost: localhost\r\n\r\n" | nc local:/var/run/docker.sock 80
```

```
HTTP/1.1 500 Internal Server Error
Api-Version: 1.43
Content-Type: application/json
Docker-Experimental: false
Ostype: linux
Server: Docker/24.0.0 (linux)
Date: Wed, 24 May 2023 07:59:10 GMT
Content-Length: 31

{"message":"context canceled"}
```

I can't find out what is going wrong. I can't find any useful information from the docker logs.

However, I switched to curl, and that works fine.
```
curl -XPOST --unix-socket /var/run/docker.sock http://localhost/v1.42/containers/wallabag/start
```

**Comment by modem7** [comment]
Why not just call docker commands with the dockercli version?
