### ISSUE TITLE
mount usb hard drive from Docker Exec?

### ISSUE THREAD

**Issue by Akruidenberg** [modem7/docker-borgmatic#11]
I would like to an external hard drive from the container itself, not from the host. It would be nice to add an pre script/command to mount the drive and add an post command to umount the drive when the backup is completed. No fstab. 

What are the proper steps to get this running?

**Comment by modem7** [comment]
Not quite sure tbf.

In terms of scripts, it's easy enough to create a script to mount the drive onto the host before the backup, and unmount it after the backup.

You'd then need to script a way to mount it within the docker container.

Is there a particular reason why you want to mount/unmount outside of backups? (eg are you going to be running it on a cron job or manually? If it's manually, then the easiest thing to do would be to have a separate compose.yml).

**Comment by Akruidenberg** [comment]
Fixed
