### ISSUE TITLE
Custom pg_dump version

### ISSUE THREAD

**Issue by zjean** [modem7/docker-borgmatic#133]
Hi,
I am thankfully using this docker image, however I run into an issue.
I use multiple postgres containers, and like to backup them using the postgresql_databases hook.
A new docker stack I use, uses postgres 16, however the pg_dump version in the borgmatic container seems to be 15.

I get this error during my backup:

```
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.1; pg_dump version: 15.5
```
Any ideas how I can fix this?

**Comment by modem7** [comment]
Can you try the latest version please?
