### ISSUE TITLE
pg_dump v17 - version mismatch

### ISSUE THREAD

**Issue by Rigel772** [modem7/docker-borgmatic#156]
I am getting:
```
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.0 (Debian 17.0-1.pgdg120+1); pg_dump version: 16.4
hatchlon_dbs_configs on BorgBase: Error running actions for repository
Command 'pg_dump --no-password --clean --if-exists --host 127.0.0.1 --port 5408 --username o --format plain dev_db > /run/user/0/./borgmatic/postgresql_databases/127.0.0.1/dev_db' returned non-zero exit status 1.
```
Any suggestions what can I do?
Thanks a lot

**Comment by modem7** [comment]
For now, you should be able to use the extra_packages variable to install the more up to date version. 

E.g.
`EXTRA_PKGS: postgresql17-client`

**Comment by Rigel772** [comment]
Thanks for super fast response
Added the extra_packages var to docker-compose but does not seem to make any difference.
When I try in the container directly:
```
/ # apk add postgresql17-client
ERROR: unable to select packages:
  postgresql17-client (no such package):
    required by: world[postgresql17-client]
```

Sot it looks like not a solution for now... or I am missing something?
Excuse my ignorance pls

**Comment by modem7** [comment]
Heya,

You're definitely not missing anything. 

I just had a look at the Alpine packages, and it looks like the 17 client is only available on edge currently, so we'll need to wait for that to be released before you can use it. 

https://pkgs.alpinelinux.org/packages?name=postgresql17-client&branch=edge&repo=&arch=x86_64&origin=&flagged=&maintainer=

**Comment by Rigel772** [comment]
Thank you

**Comment by modem7** [comment]
The only real solution currently that I can see is to fork this Docker image, and either:
1. Change the base image to edge (https://github.com/modem7/docker-borgmatic/blob/master/base-fullbuild/Dockerfile#L3)
2. Add the edge repo to the current image. 

Of either option, number 1 is probably the simplest with the fewest potential issues.

**Comment by modem7** [comment]
I've just updated to Alpine 3.20 - give it a whirl.
