### ISSUE TITLE
Not compatible with Postgress 17x 

### ISSUE THREAD

**Issue by Akruidenberg** [modem7/docker-borgmatic#159]
This docker version does not support versions higher than version Postgres 16.5. is it possible to update this image to the latest version of postgres-client?

**_pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.1; pg_dump version: 16.5_**

Thanks!

**Comment by modem7** [comment]
Please see https://github.com/modem7/docker-borgmatic/issues/156.

Once Alpine has a version with postgres 17 client, we can upgrade to it.

**Comment by modem7** [comment]
I've just updated to Alpine 3.20 - give it a whirl.

**Comment by Akruidenberg** [comment]
Looks like its available now with python.

**Comment by modem7** [comment]
Unfortunately it seems another dependency (libacl), is not available yet on 3.21. 

https://pkgs.alpinelinux.org/packages?name=libacl&branch=v3.21&repo=&arch=x86_64&origin=&flagged=&maintainer=

Once this is available, I'll be able to build the image with 3.21.

I'll re-open this issue in the meantime so we can have visibility.

**Comment by modem7** [comment]
Great spot! I'll get that update running now. 

Sincerely appreciate it!

**Comment by modem7** [comment]
New build tested successfully on two VM's.
