### ISSUE TITLE
Library libxxhash missing after borgmatic update to 1.7.7-1.2.3

### ISSUE THREAD

**Issue by KiwiActinidia** [modem7/docker-borgmatic#83]
After pulling an update to my borgmatic, during startup borg show this error:
  ```
 File "/usr/local/lib/python3.11/site-packages/borg/archiver.py", line 39, in <module> 
     from .algorithms.checksums import crc32
     ImportError: Error loading shared library libxxhash.so.0: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/borg/algorithms/checksums.cpython-311-x86_64-linux-musl.so) 
```

Googling on internet i found the reference to this Package: libxxhash
Accessing borgmatic console and executing 
`apk add libxxhash
`
borg program execute normally.

Regards
Alessandro

**Comment by modem7** [comment]
Heya, 

I'm literally looking at this issue this afternoon and came to the same conclusion. For some reason, it's not including in the build. 

In the meantime, to make sure your backups keep working, could you do:

`docker exec Borgmatic sh -c "apk add libxxhash"`

Where `Borgmatic` is the name of your container. 

I'll get this resolved asap.
