### ISSUE TITLE
Question: How to persist consistency check frequency?

### ISSUE THREAD

**Issue by mrclschstr** [modem7/docker-borgmatic#90]
Just a quick question: I usually run consistency checks with my repositories once a week as those checks take quite some time. In the borgmatic logs I can see the following (excerpt):

```
Skipping repository check due to configured frequency; 6 days, 14:25:43.498865 until next check
```

After updating (and therefore recreating) the container it seems that borgmatic forgot when the last consistency check took place. I can see the following in the borgmatic logs (excerpt):

```
Ignoring consistency prefix option, as "archives" or "data" are not in consistency checks
Remote: Starting repository check
Remote: finished segment check at segment 130
Remote: Starting repository index check
Remote: Index object count match.
Remote: Finished full repository check, no problems found.
```

I have mounted volumes for the following paths:

  * `/mnt/source`
  * `/etc/borgmatic.d`
  * `/root/.ssh`
  * `/root/.cache/borg`
  * `/root/.config/borg`

I seems that some volume is missing? Do you know where borgmatic stores the information when the last consistency check took place?

**Comment by modem7** [comment]
Heya!

Aye, that seems to be a bug in the latest version, please see https://projects.torsion.org/borgmatic-collective/borgmatic/issues/662

Hopefully it should be resolved in the next version!

Cheers!

**Comment by modem7** [comment]
> I think the path `/root/.borgmatic` is not as deprecated as you mention it in your [README](https://github.com/modem7/docker-borgmatic#rootborgmatic). Removing this volume from the config makes borgmatic forget the last consistency check after recreating the container.

You may very well be right. I've just been notified about https://github.com/borgmatic-collective/docker-borgmatic/issues/211 so I'll need to do some thinking and update things.

**Comment by modem7** [comment]
I've updated the readme, updated the Dockerfile and made sure that that volume is still available. 

Good catch.

Let me know if you're still having issues.

I'll close this off,
