### ISSUE TITLE
Still /root/.borgmatic in dockerfile

### ISSUE THREAD

**Issue by TermeHansen** [modem7/docker-borgmatic#96]
When running with docker compose, I still get a volume deployed each time, which comes from:

https://github.com/modem7/docker-borgmatic/blob/c96322b15e79a2625448cdacb16555975218f0ea/base-fullbuild/Dockerfile#L7

You state `/root/.borgmatic` is deprecated, so that should be removed I guess.

**Comment by modem7** [comment]
Will close this in favour of above comment.

I need to get some time to sort this out, unfortunately work is taking precedence.
